export const ALL_RESULT_REQUEST = "ALL_RESULT_REQUEST";
export const ALL_RESULT_SUCCESS = "ALL_RESULT_SUCCESS";
export const ALL_RESULT_FAIL = "ALL_RESULT_FAIL";

export const NEW_RESULT_REQUEST = "NEW_RESULT_REQUEST";
export const NEW_RESULT_SUCCESS = "NEW_RESULT_SUCCESS";
export const NEW_RESULT_FAIL = "NEW_RESULT_FAIL";
export const NEW_RESULT_RESET = "NEW_RESULT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";