export const ALL_STUDENT_REQUEST = "ALL_STUDENT_REQUEST"
export const ALL_STUDENT_SUCCESS = "ALL_STUDENT_SUCCESS"
export const ALL_STUDENT_FAIL = "ALL_STUDENT_FAIL"


export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST"
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS"
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL"


export const NEW_STUDENT_REQUEST = "NEW_STUDENT_REQUEST";
export const NEW_STUDENT_SUCCESS = "NEW_STUDENT_SUCCESS";
export const NEW_STUDENT_FAIL = "NEW_STUDENT_FAIL";
export const NEW_STUDENT_RESET = "NEW_STUDENT_RESET";


export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS" 