export const ALL_STUDENT_REQUEST = "ALL_STUDENT_REQUEST"
export const ALL_STUDENT_SUCCESS = "ALL_STUDENT_SUCCESS"
export const ALL_STUDENT_FAIL = "ALL_STUDENT_FAIL"

export const NEW_STUDENT_REQUEST = "NEW_STUDENT_REQUEST";
export const NEW_STUDENT_SUCCESS = "NEW_STUDENT_SUCCESS";
export const NEW_STUDENT_FAIL = "NEW_STUDENT_FAIL";
export const NEW_STUDENT_RESET = "NEW_STUDENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS" 